version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: myslq-sicat
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb-sicat    
    ports:
      - "3308:27017"
    volumes:
      - api_mongo-data:/data/db

volumes:
  mysql-data:
    external: true  # Asegúrate de que el volumen se cree y se maneje por Docker Compose
  api_mongo-data: #
  external: true